//! Data, configuration, query, and DevOps DSL language specifications.

use super::types::LanguageSpec;
use crate::parser::code::languages::SupportedLanguage;

pub(super) static BASH_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Bash,
    function_node_kinds: &["function_definition"],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &[],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: Some("name"),
    comment_prefix: "#",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function_definition"],
    import_node_kinds: &["command"],
    call_node_kinds: &["command"],
};

pub(super) static SQL_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Sql,
    function_node_kinds: &["create_function_statement", "create_procedure_statement"],
    method_node_kinds: &[],
    class_node_kinds: &[
        "create_table_statement",
        "create_view_statement",
        "create_table",
        "create_view",
    ],
    struct_node_kinds: &[],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &["create_schema_statement"],
    type_alias_node_kinds: &[],
    name_field: Some("name"),
    comment_prefix: "--",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["create_function_statement", "create_procedure_statement"],
    import_node_kinds: &[],
    call_node_kinds: &["function_call"],
};

pub(super) static YAML_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Yaml,
    function_node_kinds: &[],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &["block_mapping_pair"],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &["document"],
    type_alias_node_kinds: &[],
    name_field: Some("key"),
    comment_prefix: "#",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["block_mapping_pair"],
    import_node_kinds: &[],
    call_node_kinds: &[],
};

pub(super) static DOCKERFILE_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Dockerfile,
    function_node_kinds: &[
        "instruction",
        "run_instruction",
        "cmd_instruction",
        "entrypoint_instruction",
    ],
    method_node_kinds: &[],
    class_node_kinds: &["from_instruction"],
    struct_node_kinds: &[],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: None,
    comment_prefix: "#",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["from_instruction"],
    import_node_kinds: &["from_instruction"],
    call_node_kinds: &["run_instruction"],
};

pub(super) static PROTO_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Proto,
    function_node_kinds: &["rpc"],
    method_node_kinds: &[],
    class_node_kinds: &["message", "service"],
    struct_node_kinds: &[],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &["enum"],
    module_node_kinds: &["package"],
    type_alias_node_kinds: &[],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["rpc"],
    import_node_kinds: &["import"],
    call_node_kinds: &["rpc"],
};

pub(super) static SOLIDITY_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Solidity,
    function_node_kinds: &["function_definition"],
    method_node_kinds: &[],
    class_node_kinds: &["contract_declaration", "interface_declaration", "library_declaration"],
    struct_node_kinds: &["struct_declaration"],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &["enum_declaration"],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function_definition"],
    import_node_kinds: &["import_directive"],
    call_node_kinds: &["function_call"],
};

pub(super) static HTML_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Html,
    function_node_kinds: &[],
    method_node_kinds: &[],
    class_node_kinds: &["element", "script_element", "style_element"],
    struct_node_kinds: &[],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: Some("tag_name"),
    comment_prefix: "<!--",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["element"],
    import_node_kinds: &[],
    call_node_kinds: &[],
};

pub(super) static CSS_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Css,
    function_node_kinds: &[],
    method_node_kinds: &[],
    class_node_kinds: &["rule_set", "media_statement", "keyframes_statement"],
    struct_node_kinds: &[],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: None,
    comment_prefix: "/*",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["rule_set"],
    import_node_kinds: &["import_statement"],
    call_node_kinds: &["call_expression"],
};

pub(super) static JSON_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Json,
    function_node_kinds: &[],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &["pair", "object"],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: Some("key"),
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["pair"],
    import_node_kinds: &[],
    call_node_kinds: &[],
};

pub(super) static TOML_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Toml,
    function_node_kinds: &[],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &["table", "pair"],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: Some("key"),
    comment_prefix: "#",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["table"],
    import_node_kinds: &[],
    call_node_kinds: &[],
};

pub(super) static CMAKE_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Cmake,
    function_node_kinds: &["function_def", "macro_def"],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &[],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: None,
    comment_prefix: "#",
    doc_comment_kinds: &["line_comment", "bracket_comment"],
    callable_node_kinds: &["function_def", "macro_def"],
    import_node_kinds: &["normal_command"],
    call_node_kinds: &["normal_command"],
};

pub(super) static MAKE_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Make,
    function_node_kinds: &[],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &["rule"],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: None,
    comment_prefix: "#",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["rule"],
    import_node_kinds: &["include_directive"],
    call_node_kinds: &["recipe"],
};

pub(super) static GRAPHQL_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Graphql,
    function_node_kinds: &["field_definition"],
    method_node_kinds: &[],
    class_node_kinds: &["object_type_definition", "interface_type_definition", "schema_definition"],
    struct_node_kinds: &[],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &["enum_type_definition"],
    module_node_kinds: &[],
    type_alias_node_kinds: &["union_type_definition"],
    name_field: Some("name"),
    comment_prefix: "#",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["field_definition"],
    import_node_kinds: &[],
    call_node_kinds: &["field"],
};

pub(super) static HCL_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Hcl,
    function_node_kinds: &["attribute"],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &["block"],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: None,
    comment_prefix: "#",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["block"],
    import_node_kinds: &[],
    call_node_kinds: &["function_call"],
};

pub(super) static NIX_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Nix,
    function_node_kinds: &["function_expression", "binding"],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &["attrset_expression", "rec_attrset_expression"],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: None,
    comment_prefix: "#",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function_expression", "binding"],
    import_node_kinds: &[],
    call_node_kinds: &["apply_expression"],
};

pub(super) static TLAPLUS_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Tlaplus,
    function_node_kinds: &["operator_definition", "function_definition"],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &[],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &["module"],
    type_alias_node_kinds: &[],
    name_field: Some("name"),
    comment_prefix: "\\*",
    doc_comment_kinds: &["comment", "block_comment"],
    callable_node_kinds: &["operator_definition", "function_definition"],
    import_node_kinds: &["extends", "instance"],
    call_node_kinds: &["bound_infix_op"],
};

pub(super) static BICEP_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Bicep,
    function_node_kinds: &["parameter_declaration", "variable_declaration", "output_declaration"],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &["resource_declaration", "module_declaration"],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["resource_declaration", "module_declaration"],
    import_node_kinds: &["import_declaration"],
    call_node_kinds: &["function_call"],
};

pub(super) static POWERSHELL_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::PowerShell,
    function_node_kinds: &["function_statement"],
    method_node_kinds: &[],
    class_node_kinds: &["class_statement"],
    struct_node_kinds: &[],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &["enum_statement"],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: Some("name"),
    comment_prefix: "#",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function_statement"],
    import_node_kinds: &["using_statement"],
    call_node_kinds: &["command", "invocable_expression"],
};
