//! Functional and dynamic scripting language specifications (Elixir, Lua, OCaml, Haskell, Julia, R, Starlark, Gleam).

use super::types::LanguageSpec;
use crate::parser::code::languages::SupportedLanguage;

pub(super) static ELIXIR_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Elixir,
    function_node_kinds: &["call"],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &[],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: None,
    comment_prefix: "#",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["call"],
    import_node_kinds: &["call"],
    call_node_kinds: &["call"],
};

pub(super) static LUA_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Lua,
    function_node_kinds: &["function_declaration", "local_function"],
    method_node_kinds: &["function_definition"],
    class_node_kinds: &[],
    struct_node_kinds: &[],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: Some("name"),
    comment_prefix: "--",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function_declaration", "local_function"],
    import_node_kinds: &["function_call"],
    call_node_kinds: &["function_call"],
};

pub(super) static OCAML_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Ocaml,
    function_node_kinds: &["let_binding", "value_definition"],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &[],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &["module_definition", "module_binding"],
    type_alias_node_kinds: &["type_definition"],
    name_field: Some("name"),
    comment_prefix: "(*",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["let_binding", "value_definition"],
    import_node_kinds: &["open_statement"],
    call_node_kinds: &["application_expression"],
};

pub(super) static HASKELL_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Haskell,
    function_node_kinds: &["function", "bind", "signature"],
    method_node_kinds: &[],
    class_node_kinds: &["class_declaration"],
    struct_node_kinds: &["data_declaration", "newtype_declaration"],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &["module_declaration"],
    type_alias_node_kinds: &["type_synonym"],
    name_field: Some("name"),
    comment_prefix: "--",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function", "bind"],
    import_node_kinds: &["import"],
    call_node_kinds: &["apply"],
};

pub(super) static JULIA_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Julia,
    function_node_kinds: &["function_definition", "short_function_definition"],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &["struct_definition"],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &["module_definition"],
    type_alias_node_kinds: &[],
    name_field: Some("name"),
    comment_prefix: "#",
    doc_comment_kinds: &["line_comment", "block_comment"],
    callable_node_kinds: &["function_definition", "short_function_definition"],
    import_node_kinds: &["using_statement", "import_statement"],
    call_node_kinds: &["call_expression"],
};

pub(super) static R_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::R,
    function_node_kinds: &["function_definition"],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &[],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: Some("name"),
    comment_prefix: "#",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function_definition"],
    import_node_kinds: &["call"],
    call_node_kinds: &["call"],
};

pub(super) static STARLARK_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Starlark,
    function_node_kinds: &["function_definition"],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &[],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: Some("name"),
    comment_prefix: "#",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function_definition"],
    import_node_kinds: &[],
    call_node_kinds: &["call"],
};

pub(super) static GLEAM_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Gleam,
    function_node_kinds: &["function"],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &["type_definition"],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &["type_alias"],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function"],
    import_node_kinds: &["import"],
    call_node_kinds: &["function_call"],
};
