//! Managed and modern application language specifications (TS/JS, Python, Go, Java, C#, Ruby, PHP, Swift, Kotlin, Scala, Dart).

use super::types::LanguageSpec;
use crate::parser::code::languages::SupportedLanguage;

pub(super) static TS_JS_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::TypeScript,
    function_node_kinds: &["function_declaration", "function"],
    method_node_kinds: &["method_definition"],
    class_node_kinds: &["class_declaration", "class"],
    struct_node_kinds: &[],
    interface_node_kinds: &["interface_declaration"],
    trait_node_kinds: &[],
    enum_node_kinds: &["enum_declaration"],
    module_node_kinds: &["module", "internal_module"],
    type_alias_node_kinds: &["type_alias_declaration"],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &[
        "function_declaration",
        "method_definition",
        "function",
        "arrow_function",
    ],
    import_node_kinds: &["import_statement"],
    call_node_kinds: &["call_expression", "new_expression"],
};

pub(super) static TSX_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Tsx,
    function_node_kinds: &["function_declaration", "function"],
    method_node_kinds: &["method_definition"],
    class_node_kinds: &["class_declaration", "class"],
    struct_node_kinds: &[],
    interface_node_kinds: &["interface_declaration"],
    trait_node_kinds: &[],
    enum_node_kinds: &["enum_declaration"],
    module_node_kinds: &["module", "internal_module"],
    type_alias_node_kinds: &["type_alias_declaration"],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &[
        "function_declaration",
        "method_definition",
        "function",
        "arrow_function",
    ],
    import_node_kinds: &["import_statement"],
    call_node_kinds: &["call_expression", "new_expression"],
};

pub(super) static PYTHON_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Python,
    function_node_kinds: &["function_definition"],
    method_node_kinds: &[],
    class_node_kinds: &["class_definition"],
    struct_node_kinds: &[],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: Some("name"),
    comment_prefix: "#",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function_definition"],
    import_node_kinds: &["import_statement", "import_from_statement"],
    call_node_kinds: &["call"],
};

pub(super) static GO_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Go,
    function_node_kinds: &["function_declaration"],
    method_node_kinds: &["method_declaration"],
    class_node_kinds: &[],
    struct_node_kinds: &["type_declaration", "type_spec"],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function_declaration", "method_declaration"],
    import_node_kinds: &["import_declaration", "import_spec"],
    call_node_kinds: &["call_expression"],
};

pub(super) static JAVA_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Java,
    function_node_kinds: &["method_declaration", "constructor_declaration"],
    method_node_kinds: &[],
    class_node_kinds: &["class_declaration"],
    struct_node_kinds: &["record_declaration"],
    interface_node_kinds: &["interface_declaration"],
    trait_node_kinds: &[],
    enum_node_kinds: &["enum_declaration"],
    module_node_kinds: &["package_declaration"],
    type_alias_node_kinds: &[],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["line_comment", "block_comment"],
    callable_node_kinds: &["method_declaration", "constructor_declaration"],
    import_node_kinds: &["import_declaration"],
    call_node_kinds: &["method_invocation"],
};

pub(super) static CSHARP_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::CSharp,
    function_node_kinds: &["method_declaration", "constructor_declaration"],
    method_node_kinds: &[],
    class_node_kinds: &["class_declaration"],
    struct_node_kinds: &["struct_declaration", "record_declaration"],
    interface_node_kinds: &["interface_declaration"],
    trait_node_kinds: &[],
    enum_node_kinds: &["enum_declaration"],
    module_node_kinds: &["namespace_declaration"],
    type_alias_node_kinds: &[],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["method_declaration", "constructor_declaration"],
    import_node_kinds: &["using_directive"],
    call_node_kinds: &["invocation_expression"],
};

pub(super) static RUBY_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Ruby,
    function_node_kinds: &[],
    method_node_kinds: &["method", "singleton_method"],
    class_node_kinds: &["class"],
    struct_node_kinds: &[],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &["module"],
    type_alias_node_kinds: &[],
    name_field: Some("name"),
    comment_prefix: "#",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["method", "singleton_method"],
    import_node_kinds: &["call"],
    call_node_kinds: &["call", "method_call"],
};

pub(super) static PHP_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Php,
    function_node_kinds: &["function_definition"],
    method_node_kinds: &["method_declaration"],
    class_node_kinds: &["class_declaration"],
    struct_node_kinds: &[],
    interface_node_kinds: &["interface_declaration"],
    trait_node_kinds: &["trait_declaration"],
    enum_node_kinds: &["enum_declaration"],
    module_node_kinds: &["namespace_definition"],
    type_alias_node_kinds: &[],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function_definition", "method_declaration"],
    import_node_kinds: &["namespace_use_declaration"],
    call_node_kinds: &["function_call_expression", "member_call_expression"],
};

pub(super) static SWIFT_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Swift,
    function_node_kinds: &["function_declaration"],
    method_node_kinds: &[],
    class_node_kinds: &["class_declaration"],
    struct_node_kinds: &["struct_declaration"],
    interface_node_kinds: &["protocol_declaration"],
    trait_node_kinds: &[],
    enum_node_kinds: &["enum_declaration"],
    module_node_kinds: &[],
    type_alias_node_kinds: &["typealias_declaration"],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function_declaration", "init_declaration"],
    import_node_kinds: &["import_declaration"],
    call_node_kinds: &["call_expression"],
};

pub(super) static KOTLIN_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Kotlin,
    function_node_kinds: &["function_declaration"],
    method_node_kinds: &[],
    class_node_kinds: &["class_declaration"],
    struct_node_kinds: &["object_declaration"],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &["enum_entry"],
    module_node_kinds: &["package_header"],
    type_alias_node_kinds: &["type_alias"],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["line_comment", "multiline_comment"],
    callable_node_kinds: &["function_declaration", "secondary_constructor"],
    import_node_kinds: &["import_header"],
    call_node_kinds: &["call_expression"],
};

pub(super) static SCALA_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Scala,
    function_node_kinds: &["function_definition", "function_declaration"],
    method_node_kinds: &[],
    class_node_kinds: &["class_definition"],
    struct_node_kinds: &["object_definition"],
    interface_node_kinds: &[],
    trait_node_kinds: &["trait_definition"],
    enum_node_kinds: &["enum_definition"],
    module_node_kinds: &["package_clause"],
    type_alias_node_kinds: &["type_definition"],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function_definition"],
    import_node_kinds: &["import_declaration"],
    call_node_kinds: &["call_expression"],
};

pub(super) static DART_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Dart,
    function_node_kinds: &["function_signature", "method_signature"],
    method_node_kinds: &[],
    class_node_kinds: &["class_definition"],
    struct_node_kinds: &[],
    interface_node_kinds: &[],
    trait_node_kinds: &["mixin_declaration"],
    enum_node_kinds: &["enum_declaration"],
    module_node_kinds: &["library_directive"],
    type_alias_node_kinds: &["type_alias"],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function_signature", "method_signature"],
    import_node_kinds: &["import_or_export"],
    call_node_kinds: &["method_invocation", "function_expression_invocation"],
};
