//! Systems and low-level language specifications (Rust, C, C++, Zig, CUDA, Verilog, D, WGSL).

use super::types::LanguageSpec;
use crate::parser::code::languages::SupportedLanguage;

pub(super) static RUST_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Rust,
    function_node_kinds: &["function_item"],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &["struct_item"],
    interface_node_kinds: &[],
    trait_node_kinds: &["trait_item"],
    enum_node_kinds: &["enum_item"],
    module_node_kinds: &["mod_item", "impl_item"],
    type_alias_node_kinds: &["type_item"],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["line_comment", "block_comment"],
    callable_node_kinds: &["function_item"],
    import_node_kinds: &["use_declaration"],
    call_node_kinds: &["call_expression", "method_call_expression"],
};

pub(super) static C_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::C,
    function_node_kinds: &["function_definition"],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &["struct_specifier"],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &["enum_specifier"],
    module_node_kinds: &[],
    type_alias_node_kinds: &["type_definition"],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function_definition"],
    import_node_kinds: &["preproc_include"],
    call_node_kinds: &["call_expression"],
};

pub(super) static CPP_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Cpp,
    function_node_kinds: &["function_definition"],
    method_node_kinds: &[],
    class_node_kinds: &["class_specifier"],
    struct_node_kinds: &["struct_specifier"],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &["enum_specifier"],
    module_node_kinds: &["namespace_definition"],
    type_alias_node_kinds: &["type_definition", "alias_declaration"],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function_definition"],
    import_node_kinds: &["preproc_include"],
    call_node_kinds: &["call_expression"],
};

pub(super) static ZIG_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Zig,
    function_node_kinds: &["fn_proto", "fn_decl"],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &["container_decl"],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &[],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["line_comment", "doc_comment"],
    callable_node_kinds: &["fn_proto", "fn_decl"],
    import_node_kinds: &["builtin_call"],
    call_node_kinds: &["call_expression"],
};

pub(super) static CUDA_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Cuda,
    function_node_kinds: &["function_definition"],
    method_node_kinds: &[],
    class_node_kinds: &["class_specifier"],
    struct_node_kinds: &["struct_specifier"],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &["enum_specifier"],
    module_node_kinds: &["namespace_definition"],
    type_alias_node_kinds: &["type_definition", "alias_declaration"],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function_definition"],
    import_node_kinds: &["preproc_include"],
    call_node_kinds: &["call_expression"],
};

pub(super) static VERILOG_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Verilog,
    function_node_kinds: &["task_declaration", "function_declaration"],
    method_node_kinds: &[],
    class_node_kinds: &["class_declaration"],
    struct_node_kinds: &[],
    interface_node_kinds: &["interface_declaration"],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &["module_declaration"],
    type_alias_node_kinds: &[],
    name_field: None,
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["task_declaration", "function_declaration", "module_declaration"],
    import_node_kinds: &["include_compiler_directive"],
    call_node_kinds: &["system_tf_call", "tf_call"],
};

pub(super) static D_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::D,
    function_node_kinds: &["function_declaration"],
    method_node_kinds: &[],
    class_node_kinds: &["class_declaration"],
    struct_node_kinds: &["struct_declaration"],
    interface_node_kinds: &["interface_declaration"],
    trait_node_kinds: &[],
    enum_node_kinds: &["enum_declaration"],
    module_node_kinds: &["module_declaration"],
    type_alias_node_kinds: &["alias_declaration"],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function_declaration"],
    import_node_kinds: &["import_declaration"],
    call_node_kinds: &["call_expression"],
};

pub(super) static WGSL_SPEC: LanguageSpec = LanguageSpec {
    language: SupportedLanguage::Wgsl,
    function_node_kinds: &["function_declaration"],
    method_node_kinds: &[],
    class_node_kinds: &[],
    struct_node_kinds: &["struct_declaration"],
    interface_node_kinds: &[],
    trait_node_kinds: &[],
    enum_node_kinds: &[],
    module_node_kinds: &[],
    type_alias_node_kinds: &["type_alias_declaration"],
    name_field: Some("name"),
    comment_prefix: "//",
    doc_comment_kinds: &["comment"],
    callable_node_kinds: &["function_declaration"],
    import_node_kinds: &["enable_directive"],
    call_node_kinds: &["call_expression"],
};
